### ISSUE TITLE
The 1.21 fabric version of this mod doesn't add anything.

### ISSUE THREAD

**Issue by HitchEdits** [tom5454/Toms-Trading-Network#11] opened 2024-07-01 06:56 UTC
I cannot find any vending machine blocks, or any block relating to Tom's Trading Network Mod in JEI when playing with the 1.21 fabric version of the mod. The NeoForge version does seem to work in the 40 seconds I spent to test it, but unfortunately I'm not playing with NeoForge mods and it isn't an option.

**Comment by tom5454** [comment] 2024-07-02 14:09
Duplicate of #9
The creative tab isn't showing up, but the item is craftable.

**Closed by tom5454** 2024-07-02 14:09 UTC
