### ISSUE TITLE
Latest version does not work on 1.21.

### ISSUE THREAD

**Issue by cgileslanecc** [tom5454/Toms-Trading-Network#10] opened 2024-07-01 06:14 UTC
It simply does not show up in JEI or creative menu on the latest version1.21-0.2.15 Fabric (1.21).

**Comment by tom5454** [comment] 2024-07-02 14:09
Duplicate of #9
The creative tab isn't showing up, but the item is craftable.

**Closed by tom5454** 2024-07-02 14:09 UTC
